@baseUrl = https://localhost:5151

@projectId = f5aae296-97dc-4a2b-a15a-b20ce4780d3a
@taskId = b7cc98df-bcce-4bed-be26-d734797549c8


###



###

###
POST {{baseUrl}}/api/token/generate 
Content-Type: application/json; 

{
    "Id":"b7e15162-8e67-4e4b-9c1a-1c2b3d4e5f6a", 
    "FirstName":"khalil",
    "LastName":"bachir",
    "Email":"khalil98dev@gmail.com",
    "Permissions": 
    [
        "project:create",
        "project:read"
    ], 
    "Roles" : [
        "Admin"
    ]
    
}

###
POST {{baseUrl}}/api/token/generate
content-type: application/json

{
  "Id": "79410514-0136-4442-be9b-01f097c57f7a",
  "FirstName": "Primary",
  "LastName": "Manager",
  "Email": "pm@localhost",
  "Permissions": [
    "project:create",
    "project:read",
    "project:update",
    "project:delete",
    "project:assign_member",
    "project:manage_budget",
    "task:create",
    "task:read",
    "task:update",
    "task:delete",
    "task:assign_user",
    "task:update_status"
  ],
  "Roles": [
    "ProjectManager"
  ]
}



###
GET {{baseUrl}}/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiN2UxNTE2Mi04ZTY3LTRlNGItOWMxYS0xYzJiM2Q0ZTVmNmEiLCJlbWFpbCI6ImtoYWxpbDk4ZGV2QGdtYWlsLmNvbSIsImZhbWlseV9uYW1lIjoiYmFjaGlyIiwiZ2l2ZW5fbmFtZSI6ImtoYWxpbCIsInJvbGUiOiJBZG1pbiIsIlBlcm1pc3Npb24iOlsicHJvamVjdDpjcmVhdGUiLCJwcm9qZWN0OnJlYWQiXSwibmJmIjoxNzU1MzM5Mjc0LCJleHAiOjE3NTUzMzkzMzQsImlhdCI6MTc1NTMzOTI3NCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.B69iR-vAET2qbd6E-SjjccAUfjVrRn0sOIebW3lT7Qc
###
GET {{baseUrl}}/api/projects/{{projectId}}

###
POST {{baseUrl}}/api/projects

###
PUT {{baseUrl}}/api/projects/{{projectId}}

###
DELETE {{baseUrl}}/api/projects/{{projectId}}

###
POST {{baseUrl}}/api/projects/{{projectId}}/members

###
GET {{baseUrl}}/api/projects/{{projectId}}/budget

###
POST {{baseUrl}}/api/projects/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiN2UxNTE2Mi04ZTY3LTRlNGItOWMxYS0xYzJiM2Q0ZTVmNmEiLCJlbWFpbCI6ImtoYWxpbDk4ZGV2QGdtYWlsLmNvbSIsImZhbWlseV9uYW1lIjoiYmFjaGlyIiwiZ2l2ZW5fbmFtZSI6ImtoYWxpbCIsInJvbGUiOiJBZG1pbiIsIlBlcm1pc3Npb24iOlsicHJvamVjdDpjcmVhdGUiLCJwcm9qZWN0OnJlYWQiXSwibmJmIjoxNzU1MzM5MTI4LCJleHAiOjE3NTUzMzk3MjgsImlhdCI6MTc1NTMzOTEyOCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.i3IjA-bFq-yUKtYenKDMD3D0H-Y6y034VGVO7aArP9w

###
GET {{baseUrl}}/api/projects/tasks/{{taskId}}

###
PUT {{baseUrl}}/api/projects/tasks/{{taskId}}
Content-Type: application/json

###
DELETE {{baseUrl}}/api/projects/tasks/{{taskId}}

###
POST {{baseUrl}}/api/projects/tasks/{{taskId}}/assign
Content-Type: application/json

###
PUT {{baseUrl}}/api/projects/tasks/{{taskId}}/status
Content-Type: application/json


### 
POST  {{baseUrl}}/api/token/refresh-Token 
Content-Type: application/json 

{
    "refreshToken":"b3e1c2d4-5f6a-7b8c-9d0e-1f2a3b4c5d6e" 
}
